### ISSUE TITLE
Camera view poor performance: image flickering due to resizing with uninitialized image parameters

### ISSUE THREAD

**Issue by nunoguedelha** [ami-iit/openmct#1]
Refer to https://github.com/ami-iit/yarp-openmct/issues/103.

#### Summary

The video stream visualized in the OpenMCT canvas is often flickering (the visualized values have a format "image"). Here's the exported JSON element:
```js
{"openmct":{"yarpopenmct.icubtelemetry:sens.camLeftEye":{"name":"Camera view Left eye","type":"yarpopenmct.camimage","telemetry":{"values":[{"key":"value","name":"Cam Left Eye","format":"image","hints":{"image":1}},{"key":"utc","source":"timestamp","name":"Timestamp","format":"utc","hints":{"domain":1}}]},"location":"yarpopenmct.icubtelemetry:icubtelemetry","id":"yarpopenmct.icubtelemetry:sens.camLeftEye","identifier":{"namespace":"yarpopenmct.icubtelemetry","key":"sens.camLeftEye"}}},"rootId":"yarpopenmct.icubtelemetry:sens.camLeftEye"}
```

We can notice that the flickering is due to the image side boundaries quickly switching, i.e. the image is alternating between a shrink and stretched size fitting the canvas. Refer to short video in "Additional Information" section.

#### Expected vs Current Behavior

There should be no flickering. The image should be displayed directly with its final aspect ratio, fitting the height or the width of the canvas container depending on that aspect ratio.

#### Steps to Reproduce

1. Create an "image" format telemetry entry and associate it to any streaming video with any constant aspect ratio.
2. Run the openmct client app on the browser (tested openmct tag 1.7.8 and v2.0.3)
3. Click on the mentioned telemetry entry.
4. resize the canvas such that it doesn't match the video original aspect ratio. 

#### Environment

* Open MCT Version:  (1.7.8) ab7e2c57470d3c6076459ad7e3eaa1883cc3b8b0
* Deployment Type:  YARP Javascript - OpenMCT (https://github.com/ami-iit/yarp-openmct)
* OS: macOS 10.15.7
* Browser: Chrome 101.0.4951.54, Firefox 94.0.2

<details>
<summary>`npx envinfo --system --browsers --npmPackages --binaries --languages --markdown` output</summary>

## System:
 - OS: macOS 10.15.7
 - CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
 - Memory: 13.74 GB / 64.00 GB
 - Shell: 3.2.57 - /bin/bash
## Binaries:
 - Node: 14.17.0 - ~/.nvm/versions/node/v14.17.0/bin/node
 - npm: 6.14.13 - ~/.nvm/versions/node/v14.17.0/bin/npm
## Languages:
 - Bash: 3.2.57 - /bin/bash
 - Perl: 5.34.0 - /usr/local/bin/perl
 - PHP: 7.3.29 - /usr/bin/php
 - Protoc: 3.18.1 - /Users/nunoguedelha/miniforge3/envs/robotologydeps2/bin/protoc
 - Python: 3.9.12 - /Users/nunoguedelha/miniforge3/envs/robotologydeps2/bin/python
 - Python3: 3.9.12 - /Users/nunoguedelha/miniforge3/envs/robotologydeps2/bin/python3
 - Ruby: 3.1.2 - /Users/nunoguedelha/miniforge3/envs/robotologydeps2/bin/ruby
## Browsers:
 - Chrome: 101.0.4951.54
 - Firefox: 94.0.2
 - Safari: 15.3
## npmPackages:
 - @braintree/sanitize-url: ^5.0.2 => 5.0.2 
 - angular: >=1.8.0 => 1.8.2 
 - angular-route: 1.4.14 => 1.4.14 
 - babel-eslint: 10.0.3 => 10.0.3 
 - comma-separated-values: ^3.6.4 => 3.6.4 
 - concurrently: ^3.6.1 => 3.6.1 
 - copy-webpack-plugin: ^4.5.2 => 4.6.0 
 - cross-env: ^6.0.3 => 6.0.3 
 - css-loader: ^1.0.0 => 1.0.1 
 - d3-axis: 1.0.x => 1.0.12 
 - d3-scale: 1.0.x => 1.0.7 
 - d3-selection: 1.3.x => 1.3.2 
 - eslint: 7.0.0 => 7.0.0 
 - eslint-plugin-vue: ^7.5.0 => 7.9.0 
 - eslint-plugin-you-dont-need-lodash-underscore: ^6.10.0 => 6.11.0 
 - eventemitter3: ^1.2.0 => 1.2.0 
 - exports-loader: ^0.7.0 => 0.7.0 
 - express: ^4.13.1 => 4.17.1 
 - fast-sass-loader: 1.4.6 => 1.4.6 
 - file-loader: ^1.1.11 => 1.1.11 
 - file-saver: ^1.3.8 => 1.3.8 
 - git-rev-sync: ^1.4.0 => 1.12.0 
 - glob: >= 3.0.0 => 7.1.6 
 - html-loader: ^0.5.5 => 0.5.5 
 - html2canvas: ^1.0.0-rc.7 => 1.0.0-rc.7 
 - imports-loader: ^0.8.0 => 0.8.0 
 - istanbul-instrumenter-loader: ^3.0.1 => 3.0.1 
 - jasmine-core: ^3.7.1 => 3.7.1 
 - jsdoc: ^3.3.2 => 3.6.6 
 - karma: 6.3.4 => 6.3.4 
 - karma-chrome-launcher: 3.1.0 => 3.1.0 
 - karma-cli: 2.0.0 => 2.0.0 
 - karma-coverage: 2.0.3 => 2.0.3 
 - karma-coverage-istanbul-reporter: 3.0.3 => 3.0.3 
 - karma-firefox-launcher: 2.1.1 => 2.1.1 
 - karma-html-reporter: 0.2.7 => 0.2.7 
 - karma-jasmine: 4.0.1 => 4.0.1 
 - karma-junit-reporter: 2.0.1 => 2.0.1 
 - karma-sourcemap-loader: 0.3.8 => 0.3.8 
 - karma-webpack: 4.0.2 => 4.0.2 
 - location-bar: ^3.0.1 => 3.0.1 
 - lodash: ^4.17.12 => 4.17.21 
 - markdown-toc: ^0.11.7 => 0.11.9 
 - marked: ^0.3.5 => 0.3.19 
 - mini-css-extract-plugin: ^0.4.1 => 0.4.5 
 - minimist: ^1.2.5 => 1.2.5 
 - moment: 2.25.3 => 2.25.3 
 - moment-duration-format: ^2.2.2 => 2.3.2 
 - moment-timezone: 0.5.28 => 0.5.28 
 - node-bourbon: ^4.2.3 => 4.2.8 
 - node-sass: ^4.14.1 => 4.14.1 
 - painterro: ^1.2.56 => 1.2.56 
 - plotly.js-basic-dist: ^2.5.0 => 2.6.3 
 - plotly.js-gl2d-dist: ^2.5.0 => 2.6.3 
 - printj: ^1.2.1 => 1.2.2 
 - raw-loader: ^0.5.1 => 0.5.1 
 - request: ^2.69.0 => 2.88.2 
 - split: ^1.0.0 => 1.0.1 
 - style-loader: ^1.0.1 => 1.3.0 
 - uuid: ^3.3.3 => 3.4.0 
 - v8-compile-cache: ^1.1.0 => 1.1.2 
 - vue: ^2.5.6 => 2.5.6 
 - vue-loader: ^15.2.6 => 15.9.7 
 - vue-template-compiler: 2.5.6 => 2.5.6 
 - webpack: ^4.16.2 => 4.46.0 
 - webpack-cli: ^3.1.0 => 3.3.12 
 - webpack-dev-middleware: ^3.1.3 => 3.7.3 
 - webpack-hot-middleware: ^2.22.3 => 2.25.0 
 - zepto: ^1.2.0 => 1.2.0 

</details>

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?

#### Additional Information

https://user-images.githubusercontent.com/6848872/165338437-4756b966-df28-47bd-89ce-2971c00c47d3.mp4

**Comment by nunoguedelha** [comment]
Hi @traversaro , I've filled the issue description as if I was opening it on https://github.com/nasa/openmct, just for anticipating the formatting effort. Any feedback on the clarity is welcome.

**Comment by traversaro** [comment]
Thanks, it seems fine. Perhaps the output of `npx envinfo --system --browsers --npmPackages --binaries --languages --markdown` is missing?

**Comment by nunoguedelha** [comment]
> Thanks, it seems fine. Perhaps the output of `npx envinfo --system --browsers --npmPackages --binaries --languages --markdown` is missing?

As discussed and verified in the last meeting, the output info is there.
