### ISSUE TITLE
Only the last Y-axis component of an Overlay Plot is refreshed by the Realtime-Telemetry-Plugin

### ISSUE THREAD

**Issue by nunoguedelha** [ami-iit/openmct#18]
Fixed in #20 .

## Summary

As the user clicks on any telemetry entry, this selection triggers an history request by the history-telemetry-plugin and a subscription request by the realtime-telemetry-plugin to the telemetry measurements updates through the mounted websocket. In the case of an Overlay Plot, we get the full history samples displayed on the plot canvas, for all the Y-axis plot series, but then the the realtime update of all the series but the last one (last PlotSeries index) fail.

This issue is systematically reproducible for any Overlay Plot combining any set of `yKey` components of a telemetry entry. Refer to the example screenshot at the bottom of this issue description.

## Expected vs Current Behavior

The realtime subscription should work properly for every component of the plot.

## Steps to Reproduce

1. Create an Overlay Plot
2. Add a telemetry entry three times, e.g. "IMU measurement".
3. Set the following Y axis options (`Value` field) in the form on the far right pane while still in editing mode: `value.acc.x`, `value.acc.y`, `value.acc.z`.
4. Save.

## Environment

* Open MCT Version: 1.7.8-iit, SHA 258986b86cf8c7a115b5e6d1b4cfa5e088910cae, based on 1.7.8 SHA ab7e2c57470d3c6076459ad7e3eaa1883cc3b8b0 (19 Oct 2021)
* Deployment Type: openmct-yarp
* OS: MacOS Catalina version 10.15.7
* Browser: Chrome Version 102.0.5005.115 (Official Build) (x86_64)

## Impact Check List

- [x] ~Data loss or~misrepresented data.
- [x] This never worked for Overlay Plots.
- [x] No workaround available?
- [x] Has a critical impact on Overlay Plots as we cannot combine multiple components of the same measurement.
- [x] Functional impact.

## Additional Information

Screenshot example of an Overlay Plot with failing `yKey` components updates failing.

![image](https://user-images.githubusercontent.com/6848872/177872853-0b04773e-8e55-4e2a-a90d-89e7627f0c57.png)

**Comment by nunoguedelha** [comment]
## Analysis

![image](https://user-images.githubusercontent.com/6848872/177895181-bb2ef2f6-c964-40c0-a00b-d4b19c5aad4d.png)

As soon as we click on the Overlay Plot (in our case containing three IMU components, i.e. `PlotSeries`), the `CompositionCollection.add` method starts a function calls and events sequence ending up in the call of `TelemetryAPI.prototype.subscribe(domainObject, callback, options)`, where:
- The `callback` object is **bound** to a specific `PlotSeries` **this** object among the three `PlotSeries` of the Overlay Plot (`this.domainObject.identifier.index = 0`), and directly related to the passed `domainObject`=> `domainObject.identifier.index = 0`.
   ![image](https://user-images.githubusercontent.com/6848872/177895690-5c44955c-a045-4742-acfb-9ce57eaddc06.png)
- A key is generated from the domain object identifier and the `callback` is pushed into the respective element from the `subscribeCache`
   (First element)
   ```js
            subscriber = this.subscribeCache[keyString] = {
                callbacks: [callback]
            };
   ```
   (subsequent elements)
   ```js
            subscriber.callbacks.push(callback);
   ```
- The subscribing method of the realtime-telemetry-plugin, `provider.subscribe(domainObject, function (value) {...}`, is called, binding that specific callback `function (value) {...}` to the listener associated to `domainObject.identifier.key` (= `sens.imu` in our example) by the provider in the `RealtimeTelemetryPlugin` plugin.
   ![image](https://user-images.githubusercontent.com/6848872/177897908-e1a72dbb-38e0-4302-9d70-ddc00cb6cf93.png)
- Since there is only one `listener[domainObject.identifier.key]` for any sample received by the plugin
   ![image](https://user-images.githubusercontent.com/6848872/177898096-5337742f-27c4-42df-bb97-2b456ce034fc.png)
   its value will be overwritten by the last PlotSeries instance callback `function (value) {...}`.

This mechanism explains the observed problem.

**Comment by nunoguedelha** [comment]
## Note [trap]

We had to do a quick fix due to a risky use of the instruction `map` in function `toOldFormat` of `object-utils.js`.

![image](https://user-images.githubusercontent.com/6848872/177912503-849e77c5-e7dd-4c92-8644-8ee54ed23589.png)

When mapping `model.composition` to a new `model.composition` using the callback `makeKeyString`, as we only pass the callback name to the `map` function, if `makeKeyString` can take two arguments, it will take `(value, index)` as if we had written the expanded pattern:
```js
            model.composition = model.composition.map((value, index) => makeKeyString(value, index));
```

As a result, `makeKeyString(identifier, skipIndex)` is called with `skipIndex = 0`, `1` and `2` while it was expecting a boolean.

![image](https://user-images.githubusercontent.com/6848872/177912379-83324b1b-745f-4d93-8a98-bec71ef91d76.png)

This would be avoided by re-writing the `map` pattern as:
```js
            model.composition = model.composition.map((value) => makeKeyString(value));
```

Anyway, for avoiding unexpected "misusage" of `map`, we'll explicit the function `makeKeyString` overload, by defining `makeKeyStringSkipIndex`.

**Comment by nunoguedelha** [comment]
The overall fix is working properly. Work complete.

CC @traversaro @S-Dafarra .

**Comment by S-Dafarra** [comment]
Great!
